<Project Sdk="Microsoft.NET.Sdk">

	<!-- project definition -->
	<PropertyGroup>
		<TargetFramework>$(DefaultNetVersion)</TargetFramework>
	</PropertyGroup>

	<!-- project references -->
	<ItemGroup>
		<ProjectReference Include="..\..\ToolboxAppOptions\ToolboxAppOptions.csproj" />
	</ItemGroup>

	<!-- nuget references -->
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<!-- nuget build-->
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Update="NUnit.Analyzers">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
