global using aemarcoCommons.ToolboxAppOptions;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using NUnit.Framework;
global using System;
global using ToolboxAppOptionsTests.Bases;
global using ToolboxAppOptionsTests.Services;
