<Project Sdk="Microsoft.NET.Sdk">

	<!-- project definition -->
	<PropertyGroup>
		<TargetFramework>$(DefaultNetVersion)</TargetFramework>
		<RootNamespace>aemarcoCommons.ToolboxWeb</RootNamespace>
		<AssemblyName>aemarcoCommons.ToolboxWeb</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<!-- project references -->
	<ItemGroup>
		<ProjectReference Include="..\Extensions\Extensions.csproj" />
	</ItemGroup>

	<!-- nuget references-->
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		
		<PackageReference Include="Riok.Mapperly" ExcludeAssets="runtime" PrivateAssets="all">
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Enrichers.Environment" />
		<PackageReference Include="Serilog.Enrichers.Thread" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.Async" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />

	</ItemGroup>

	<!-- proj build-->
	<PropertyGroup>
		<Description>c# web tools collection</Description>
		<PackageTags>WebTools</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="Resources\icon.png" Pack="true" PackagePath="\" />
		<None Include="Resources\LICENSE.md" Pack="true" PackagePath="\" />
		<None Include="Resources\NOTICE.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
