name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get-version.outputs.build_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # holt komplette Historie, NICHT shallow

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install NBGV
        run: dotnet tool install --global nbgv

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Show NBGV version
        run: nbgv get-version

      - name: Collect NuGet packages
        run: |
          mkdir artifacts
          copy **/bin/Release/*.nupkg artifacts/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ./artifacts

  push-nuget:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: push-to-nuget-org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: ./artifacts

      - name: Push packages to NuGet.org
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
