name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get-version.outputs.build_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Get NBGV version
        id: get-version
        run: |
          BUILD_VERSION=$(nbgv get-version --version-packaging NuGet)
          echo "Build version: $BUILD_VERSION"
          echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT

      - name: Pack NuGet packages
        run: dotnet pack **/*.csproj \
              --configuration ${{ env.BUILD_CONFIGURATION }} \
              --output ./artifacts \
              /p:Version=${{ steps.get-version.outputs.build_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ./artifacts

  push-nuget:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: push-to-nuget-org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: ./artifacts

      - name: Push packages to NuGet.org
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
